import * as go from 'gojs';
import { EventTreeEditorComponent } from './event-tree-editor.component';

type EventTreeLayoutMode = 'STANDARD' | 'CENTERED';

const SAVED_CATEGORIES = new Set(['START_POINT', 'FE_POINT', 'BRANCH', 'ANCHOR']);

export function installEventTreeLayoutToggleV2Patch(): void {
  const prototype = EventTreeEditorComponent.prototype as any;
  if (prototype.__eventTreeLayoutToggleV2Installed) return;
  prototype.__eventTreeLayoutToggleV2Installed = true;

  const originalAfterViewInit = prototype.ngAfterViewInit;
  const originalDestroy = prototype.ngOnDestroy;
  const originalApplyModel = prototype.applyModel;

  const getMode = (component: any): EventTreeLayoutMode =>
    component.__eventTreeLayoutModeV2 ?? 'STANDARD';

  const updateButtons = (component: any): void => {
    const mode = getMode(component);
    const standard = component.__eventTreeLayoutLeftButton as HTMLButtonElement | undefined;
    const centered = component.__eventTreeLayoutCenteredButtonV2 as HTMLButtonElement | undefined;

    const setState = (button: HTMLButtonElement | undefined, active: boolean): void => {
      if (!button) return;
      button.style.background = active ? '#e8f1ff' : '#ffffff';
      button.style.borderColor = active ? '#3b82f6' : '';
      button.style.color = active ? '#2563eb' : '';
      button.setAttribute('aria-pressed', active ? 'true' : 'false');
    };

    setState(standard, mode === 'STANDARD');
    setState(centered, mode === 'CENTERED');
  };

  const restoreBaseGeometry = (component: any): void => {
    const diagram = component.diagram as go.Diagram | undefined;
    if (!diagram) return;

    diagram.nodes.each((node: go.Node) => {
      const data = node.data as any;
      if (!SAVED_CATEGORIES.has(data?.category)) return;
      const baseLoc = data?.__etBaseLoc as string | undefined;
      if (baseLoc) node.location = go.Point.parse(baseLoc);
    });
  };

  const getSequenceCenters = (component: any): number[] => {
    const diagram = component.diagram as go.Diagram | undefined;
    if (!diagram) return [];

    const rowHeight = Number(component.__eventTreeViewportMetrics?.sequenceRowHeight ?? 34);
    const centers: number[] = [];
    diagram.nodes.each((node: go.Node) => {
      const data = node.data as any;
      if (data?.category === 'SEQUENCE') centers.push(node.location.y + rowHeight / 2);
    });
    return centers.sort((a, b) => a - b);
  };

  const applyLayout = (component: any): void => {
    const diagram = component.diagram as go.Diagram | undefined;
    if (!diagram) return;

    // Always begin from the exact RiskSpectrum-style geometry generated by the ET editor.
    restoreBaseGeometry(component);

    if (getMode(component) === 'CENTERED') {
      const sequenceCenters = getSequenceCenters(component);
      if (sequenceCenters.length > 1) {
        // True centered ET: keep every branch and every consequence on its original row.
        // Only move the main event-tree spine to the geometric centre of the outcomes.
        // Branches therefore fan both upward and downward without changing their topology.
        const firstY = sequenceCenters[0];
        const lastY = sequenceCenters[sequenceCenters.length - 1];
        const centerY = (firstY + lastY) / 2;

        diagram.nodes.each((node: go.Node) => {
          const data = node.data as any;
          const category = data?.category;
          const key = String(data?.key ?? '');

          if (category === 'START_POINT' || category === 'FE_POINT' || key === '__BASELINE_END__') {
            node.location = new go.Point(node.location.x, centerY);
          }
        });
      }
    }

    diagram.links.each((link: go.Link) => link.invalidateRoute());
    component.lockViewport?.();
  };

  const injectButtons = (component: any): void => {
    const shell = component.diagramDiv?.nativeElement?.closest?.('.et-shell') as HTMLElement | null;
    const toolbar = shell?.querySelector?.('.toolbar') as HTMLElement | null;
    if (!toolbar || component.__eventTreeLayoutControlsV2) return;

    const controls = document.createElement('span');
    controls.dataset['etLayoutV2'] = 'true';
    controls.style.display = 'inline-flex';
    controls.style.alignItems = 'center';
    controls.style.gap = '7px';

    const makeButton = (
      title: string,
      aria: string,
      svgPath: string,
      mode: EventTreeLayoutMode
    ): HTMLButtonElement => {
      const button = document.createElement('button');
      button.type = 'button';
      button.title = title;
      button.setAttribute('aria-label', aria);
      button.setAttribute('aria-pressed', 'false');
      // No custom button dimensions: inherit exactly the same toolbar button
      // height, padding, border and radius as Fit and + Branch.
      button.innerHTML = `<svg viewBox="0 0 26 18" width="22" height="16" aria-hidden="true" style="display:block"><path d="${svgPath}" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"></path></svg>`;
      button.addEventListener('click', () => {
        component.__eventTreeLayoutModeV2 = mode;
        updateButtons(component);
        requestAnimationFrame(() => applyLayout(component));
      });
      return button;
    };

    // Icons reproduce the supplied reference:
    // 1) one-sided E layout, 2) centred spine with branches on both sides.
    const standard = makeButton(
      'Disposition ET actuelle',
      'Garder la disposition actuelle de l’Event Tree',
      'M8 2v14M8 3h12M8 9h9M8 15h12',
      'STANDARD'
    );
    const centered = makeButton(
      'Centrer les branches ET',
      'Centrer les branches de l’Event Tree',
      'M13 2v14M13 3h8M5 9h16M13 15h8',
      'CENTERED'
    );

    controls.append(standard, centered);
    const hint = toolbar.querySelector('.hint');
    toolbar.insertBefore(controls, hint ?? null);

    component.__eventTreeLayoutControlsV2 = controls;
    component.__eventTreeLayoutLeftButton = standard;
    component.__eventTreeLayoutCenteredButtonV2 = centered;
    component.__eventTreeLayoutModeV2 ??= 'STANDARD';
    updateButtons(component);
  };

  prototype.applyModel = function(metrics: unknown): void {
    originalApplyModel.call(this, metrics);
    const diagram = this.diagram as go.Diagram | undefined;
    if (diagram) {
      diagram.nodes.each((node: go.Node) => {
        const data = node.data as any;
        if (!SAVED_CATEGORIES.has(data?.category)) return;
        data.__etBaseLoc = go.Point.stringify(node.location);
      });
    }
    requestAnimationFrame(() => applyLayout(this));
  };

  prototype.ngAfterViewInit = function(): void {
    originalAfterViewInit.call(this);
    requestAnimationFrame(() => {
      injectButtons(this);
      applyLayout(this);
    });
  };

  prototype.ngOnDestroy = function(): void {
    (this.__eventTreeLayoutControlsV2 as HTMLElement | undefined)?.remove();
    this.__eventTreeLayoutControlsV2 = null;
    this.__eventTreeLayoutLeftButton = null;
    this.__eventTreeLayoutCenteredButtonV2 = null;
    originalDestroy.call(this);
  };
}
