import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';
import { installEventTreeDotBehaviorPatch } from './app/gojs/event-tree/event-tree-dot-behavior.patch';
import { installEventTreeHeaderDragPatch } from './app/gojs/event-tree/event-tree-header-drag.patch';
import { installEventTreeSequenceSelectionPatch } from './app/gojs/event-tree/event-tree-sequence-selection.patch';
import { installEventTreeResultsResizePatch } from './app/gojs/event-tree/event-tree-results-resize.patch';
import { installEventTreeTagPalettePatch } from './app/gojs/event-tree/event-tree-tag-palette.patch';
import { installEventTreeBrowserWidthPatch } from './app/features/event-tree/event-tree-browser-width.patch';
import { installEventTreeViewportPatch } from './app/gojs/event-tree/event-tree-viewport.patch';
import { installEventTreeBodyDensityPatch } from './app/gojs/event-tree/event-tree-body-density.patch';
import { installEventTreeBranchContextMenuPatch } from './app/gojs/event-tree/event-tree-branch-context-menu.patch';
import { installEventTreeForwardSelectionPatch } from './app/gojs/event-tree/event-tree-forward-selection.patch';
import { installEventTreeLayoutToggleV2Patch } from './app/gojs/event-tree/event-tree-layout-toggle-v2.patch';
import { installEventTreeCenteredStabilityPatch } from './app/gojs/event-tree/event-tree-centered-stability.patch';
import { installEventTreeRootCenteringPatch } from './app/gojs/event-tree/event-tree-root-centering.patch';
import { installEventTreeLayoutButtonStylePatch } from './app/gojs/event-tree/event-tree-layout-button-style.patch';
import { installEventTreeMultiBranchSelectionPatch } from './app/gojs/event-tree/event-tree-multi-branch-selection.patch';
import { installEventTreeTaggingConsistencyPatch } from './app/gojs/event-tree/event-tree-tagging-consistency.patch';
import { installEventTreeTagTogglePatch } from './app/gojs/event-tree/event-tree-tag-toggle.patch';
import { installEventTreeSelectionTaggingControllerPatch } from './app/gojs/event-tree/event-tree-selection-tagging-controller.patch';
import { installEventTreeComponentTaggingPatch } from './app/gojs/event-tree/event-tree-component-tagging.patch';
import { installEventTreePageTaggingPatch } from './app/features/event-tree/event-tree-page-tagging.patch';
import { installEventTreeNodeVisibilityPatch } from './app/gojs/event-tree/event-tree-node-visibility.patch';
import { installEventTreeCenteredBoundaryPatch } from './app/gojs/event-tree/event-tree-centered-boundary.patch';
import { installEventTreeRenderIntegrityPatch } from './app/gojs/event-tree/event-tree-render-integrity.patch';

installEventTreeDotBehaviorPatch();
installEventTreeHeaderDragPatch();
installEventTreeSequenceSelectionPatch();
installEventTreeResultsResizePatch();
installEventTreeTagPalettePatch();
installEventTreeBrowserWidthPatch();
installEventTreeViewportPatch();
installEventTreeBodyDensityPatch();
installEventTreeBranchContextMenuPatch();
installEventTreeForwardSelectionPatch();
installEventTreeLayoutToggleV2Patch();
installEventTreeCenteredStabilityPatch();
installEventTreeRootCenteringPatch();
installEventTreeLayoutButtonStylePatch();
installEventTreeMultiBranchSelectionPatch();
installEventTreeTaggingConsistencyPatch();
installEventTreeTagTogglePatch();
installEventTreeSelectionTaggingControllerPatch();
installEventTreeComponentTaggingPatch();
installEventTreePageTaggingPatch();
installEventTreeNodeVisibilityPatch();
installEventTreeCenteredBoundaryPatch();
installEventTreeRenderIntegrityPatch();

bootstrapApplication(AppComponent, appConfig).catch((error: unknown) => {
  console.error('NextPSA bootstrap failed', error);
});
